
export default{
   state: {
      types: [
         {id: 1, name: "Nəqliyyat", src: "transport-b6d3b0d89654c87e5e6eccc14a189f0aac63a305db8d9ea17b7fd5e8f86c9ed6.png"},
         {id: 2, name: "Ev və bağ üçün", src: "house-and-cottage-72199d528ba9c02c5a0e68e9e827a5430266f33bc0891753736fbf8cebaeda78.png"},
         {id: 3, name: "Elektronika", src: "consumer-electronics-e69c996065da90f20b634047a7f288fce95e3833cd2a484a054318e935440056.png"},
         {id: 4, name: "Daşınmaz əmlak", src: "real-estate-448c664dd931fd2032b4069083af014d66e8849b7f0a21c04f9728cf8846c4c8.png"},
         {id: 5, name: "Şəxsi əşyalar", src: "personal-belongings-365932589a0f8efab0e670302b820d9617aeece9157d661022d91d28e234f4b7.png"},
         {id: 6, name: "Xidmətlər və biznes", src: "services-b38955caf4a2a29ce391b9f102652c4303d33a7a177048752a9329fbc66d71c3.png"},
         {id: 7, name: "Habbi və asudə", src: "kids-hobbies-art-classes-logo_48369-10757.png"},
         {id: 8, name: "Uşaq aləmi", src: "kids-world-47a090f5755404d52e353cd3692fbf34c6e2cd03e19aa38398d0a37de53f924d.png"},
         {id: 9, name: "Heyvanlar", src: "animals.png"},
         {id: 10, name: "İş elanları", src: "job.png"}
      ],
      subTypes: [
         {id: 1, uptype: 1, name: "Ehtiyat hissələri və aksesuarlar"},
         {id: 2, uptype: 1, name: "Motosikletlər və mopedlər"},
         {id: 3, uptype: 1, name: "Avtomobillər"},
         {id: 4, uptype: 1, name: "Aqrotexnika"},
         {id: 5, uptype: 1, name: "Avtobuslar və xüsusi texnika"},
         {id: 6, uptype: 1, name: "Su nəqliyyatı"},     
         {id: 7, uptype: 2, name: "Mebellər"},
         {id: 8, uptype: 2, name: "Məişət texnikası"},
         {id: 9, uptype: 2, name: "Təmir və tikinti"},
         {id: 10, uptype: 2, name: "Qab-qacaq və mətbəx ləvazimatları"},
         {id: 11, uptype: 2, name: "Dekor və interyer"},
         {id: 12, uptype: 2, name: "Bağ və bostan"},
         {id: 13, uptype: 2, name: "Ev və bağ üçün işiqlandırma"},
         {id: 14, uptype: 2, name: "Xalçalar və aksesuarlar"},
         {id: 15, uptype: 2, name: "Ev tekstili"},
         {id: 16, uptype: 2, name: "Bitkilər"},
         {id: 17, uptype: 2, name: "Ərzaq"},
         {id: 18, uptype: 3, name: "Telefonlar"},
         {id: 19, uptype: 3, name: "Komponentlər və monitorlar("},
         {id: 20, uptype: 3, name: "Televizorlar və aksesuarlar("},
         {id: 21, uptype: 3, name: "Ofis avadanlığı və istehlak"},
         {id: 22, uptype: 3, name: "Planşet və elektron kitablar"},
         {id: 23, uptype: 3, name: "Kompüter aksesuarları"},
         {id: 24, uptype: 3, name: "Oyunlar, pultlar və proqramlar"},
         {id: 25, uptype: 3, name: "Nömrələr və SİM-kartlar"},
         {id: 26, uptype: 3, name: "Smart saat və qolbaqlar"},
         {id: 27, uptype: 3, name: "Noutbuklar və Netbuklar"},
         {id: 28, uptype: 3, name: "Audio və video"},
         {id: 29, uptype: 3, name: "Masaüstü kompüterlər"},
         {id: 30, uptype: 3, name: "Foto texnika"},
         {id: 31, uptype: 4, name: "Mənzillər"},
         {id: 32, uptype: 4, name: "Obyektlər və ofislər"},
         {id: 33, uptype: 4, name: "Villalar, bağ evləri"},
         {id: 34, uptype: 4, name: "Qarajlar"},
         {id: 35, uptype: 4, name: "Torpaq"},
         {id: 36, uptype: 4, name: "Xaricdə əmlak"},
         {id: 37, uptype: 5, name: "Geyim və ayaqqabılar"},
         {id: 38, uptype: 5, name: "Aksesuarlar"},
         {id: 39, uptype: 5, name: "Sağlamlıq və gözəllik"},
         {id: 40, uptype: 5, name: "Elektron siqaretlər və tütün qızdırıcıları"},
         {id: 41, uptype: 5, name: "Saat və zinət əşyaları"},
         {id: 42, uptype: 5, name: "İtmiş əşyalar"},
         {id: 43, uptype: 5, name: "Biznes üçün avadanlıq"},
         {id: 44, uptype: 5, name: "Nəqliyyat və logistika"},
         {id: 45, uptype: 5, name: "IT, internet, telekom"},
         {id: 46, uptype: 5, name: "Avadanlığın icarəsi"},
         {id: 47, uptype: 5, name: "Avadanlıqların quraşdırılması"},
         {id: 48, uptype: 5, name: "Gözəllik, sağlamlıq"},
         {id: 49, uptype: 5, name: "Foto və video çəkiliş xidmətləri"},
         {id: 50, uptype: 5, name: "Hüquq xidmətləri"},
         {id: 51, uptype: 6, name: "Təmir və tikinti"},
         {id: 52, uptype: 6, name: "Texnika təmiri"},
         {id: 53, uptype: 6, name: "Təlim, hazırlıq kursları"},
         {id: 54, uptype: 6, name: "Mebel yığılması və təmiri"},
         {id: 55, uptype: 6, name: "Musiqi, əyləncə və tədbirlər"},
         {id: 56, uptype: 6, name: "Təmizlik"},
         {id: 57, uptype: 6, name: "Mühasibat xidmətləri"},
         {id: 58, uptype: 6, name: "Tərcümə"},
         {id: 59, uptype: 7, name: "İdman və asudə"},
         {id: 60, uptype: 7, name: "Velosipedlər"},
         {id: 61, uptype: 7, name: "Tanışlıq"},
         {id: 62, uptype: 7, name: "Musiqi alətləri"},
         {id: 63, uptype: 7, name: "Kitab və jurnallar"},
         {id: 64, uptype: 7, name: "Biletlər və səyahət"},
         {id: 65, uptype: 7, name: "Kolleksiya"},
         {id: 66, uptype: 7, name: "Ovçuluq və balıqçılıq"},
         {id: 67, uptype: 8, name: "Uşaq geyimi"},
         {id: 68, uptype: 8, name: "Uşaq arabaları"},
         {id: 69, uptype: 8, name: "Uşaq avtomobilləri"},
         {id: 70, uptype: 8, name: "Avtomobil oturacaqları"},
         {id: 71, uptype: 8, name: "Uşaq sürüşkənləri və oyun meydançaları"},
         {id: 72, uptype: 8, name: "Oyuncaqlar"},
         {id: 73, uptype: 8, name: "Məktəblilər üçün"},
         {id: 74, uptype: 8, name: "Digər"},
         {id: 75, uptype: 8, name: "Uşaq daşıyıcıları"},
         {id: 76, uptype: 8, name: "Manejlər"},
         {id: 77, uptype: 8, name: "Uşaq çarpayıları və beşiklər"},
         {id: 78, uptype: 8, name: "Uşaq mebeli"},
         {id: 79, uptype: 8, name: "Qidalanma üçün uşaq oturacaqları"},
         {id: 80, uptype: 8, name: "Yürütəclər"},
         {id: 81, uptype: 8, name: "Uşaq qidası"},
         {id: 82, uptype: 9, name: "Quşlar"},
         {id: 83, uptype: 9, name: "Akvarium və balıqlar"},
         {id: 84, uptype: 9, name: "Dovşanlar"},
         {id: 85, uptype: 9, name: "İtlər"},
         {id: 86, uptype: 9, name: "Pişiklər"},
         {id: 87, uptype: 9, name: "Atlar"},
         {id: 88, uptype: 9, name: "Heyvanlar üçün məhsullar"},
         {id: 89, uptype: 9, name: "K/t heyvanları"},
         {id: 90, uptype: 9, name: "Gəmiricilər"},
         {id: 91, uptype: 10, name: "Vakansiyalar"},
         {id: 92, uptype: 10, name: "İş axtarıram"}
      ]
   },
   getters: {
      getTypes(state) {
         return state.types
      },
      getSubTypes(state) {
         return state.subTypes
      }

   },
   mutations: {
   },
   actions: {
   },
}
 