export default({
   state: {
      cities: [
         {id: 1, city: "Bakı"},
         {id: 2, city: "Sumqayıt"},
         {id: 3, city: "Ağcabədi"},
         {id: 4, city: "Ağdam"},
         {id: 5, city: "Ağdaş"},
         {id: 6, city: "Ağdərə"},
         {id: 7, city: "Ağstafa"},
         {id: 8, city: "Ağsu"},
         {id: 9, city: "Astara"},
         {id: 10, city: "Balakən"},
         {id: 11, city: "Beyləqan"},
         {id: 12, city: "Bərdə"},
         {id: 13, city: "Xırdalan"},
         {id: 14, city: "Gəncə"},
         {id: 15, city: "Biləsuvar"},
         {id: 16, city: "Cəbrayıl"},
         {id: 17, city: "Cəlilabad"},
         {id: 18, city: "Culfa"},
         {id: 19, city: "Daşkəsən"},
         {id: 20, city: "Füzuli"},
         {id: 21, city: "Gədəbəy"},
         {id: 22, city: "Goranboy"},
         {id: 23, city: "Göyçay"},
         {id: 24, city: "Göygöl"},
         {id: 25, city: "Quba"},
         {id: 26, city: "Xaçmaz"},
         {id: 27, city: "Göytəpə"},
         {id: 28, city: "Hacıqabul"},
         {id: 29, city: "Horadiz"},
         {id: 30, city: "İmişli"},
         {id: 31, city: "Kəlbəcər"},
         {id: 32, city: "Kürdəmir"},
         {id: 33, city: "Laçın"},
         {id: 34, city: "Lerik"},
         {id: 35, city: "Masallı"},
         {id: 36, city: "Nabran"},
         {id: 37, city: "Qəbələ"},
         {id: 37, city: "Mingəçevir"},
         {id: 39, city: "Naftalan"},
         {id: 40, city: "Naxçıvan"},
         {id: 41, city: "Neftçala"},
         {id: 42, city: "Oğuz"},
         {id: 43, city: "Ordubad"},
         {id: 44, city: "Qax"},
         {id: 45, city: "Qazax"},
         {id: 46, city: "Qobustan"},
         {id: 47, city: "Qubadlı"},
         {id: 48, city: "Saatlı"},
         {id: 49, city: "Şəki"},
         {id: 50, city: "Lənkəran"},
         {id: 51, city: "Sabirabad"},
         {id: 52, city: "Şabran"},
         {id: 53, city: "Şahbuz"},
         {id: 54, city: "Salyan"},
         {id: 55, city: "Şamaxı"},
         {id: 56, city: "Samux"},
         {id: 57, city: "Şəmkir"},
         {id: 58, city: "Şərur"},
         {id: 59, city: "Siyəzən"},
         {id: 60, city: "Şuşa"},
         {id: 61, city: "Qusar"},
         {id: 62, city: "Zaqatala"},
         {id: 63, city: "Tərtər"},
         {id: 64, city: "Tovuz"},
         {id: 65, city: "Ucar"},
         {id: 66, city: "Xankəndi"},
         {id: 67, city: "Xızı"},
         {id: 68, city: "Xocalı"},
         {id: 69, city: "Xocavənd"},
         {id: 70, city: "Xudat"},
         {id: 71, city: "Yardımlı"},
         {id: 72, city: "Yevlax"},
         {id: 73, city: "Şirvan"},
         {id: 74, city: "İsmayıllı"},
         {id: 75, city: "Zəngilan"},
         {id: 76, city: "Zərdab"},
      ]
   },
   getters: {
      allCities(state) {
         return state.cities
      }
   }
})